// @ts-check
import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import path from 'path';
import tseslint from 'typescript-eslint';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig([
  {
    ignores: [
      'dist/**',
      'eslint.config.js',
      'node_modules/**',
      // Build output. The .min.js files are pretokenised binaries and the
      // .js files are generated by ts-blank-space; neither is hand edited.
      'holotapes/**/*.js',
      'holotapes/**/*.JS',
    ],
  },
  {
    files: ['**/*.{ts,TS}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      ...tseslint.configs.stylistic,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: path.resolve(__dirname),
        allowDefaultProject: true,
        extraFileExtensions: ['.TS'],
      },
    },
    rules: {
      // Require consistently using either T[] or Array<T> for arrays.
      // @see https://typescript-eslint.io/rules/array-type/
      '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
      // any/unknown bans live in the holotapes-only block below.
      // Enforce consistent usage of type assertions.
      // @see https://typescript-eslint.io/rules/consistent-type-assertions/
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          assertionStyle: 'as',
          objectLiteralTypeAssertions: 'never',
        },
      ],
      // Enforce type definitions to consistently use either interface or type.
      // @see https://typescript-eslint.io/rules/consistent-type-definitions/
      '@typescript-eslint/consistent-type-definitions': 'error',
      // Require explicit return types on functions and class methods.
      // @see https://typescript-eslint.io/rules/explicit-function-return-type/
      '@typescript-eslint/explicit-function-return-type': [
        'error',
        { allowExpressions: true },
      ],
      // Require explicit accessibility modifiers on class properties and
      // methods.
      // @see https://typescript-eslint.io/rules/explicit-member-accessibility/
      '@typescript-eslint/explicit-member-accessibility': [
        'error',
        { accessibility: 'explicit' },
      ],
      // Require explicit return and argument types on exported functions' and
      // classes' public class methods.
      // @see https://typescript-eslint.io/rules/explicit-module-boundary-types/
      '@typescript-eslint/explicit-module-boundary-types': 'error',
      // Require a consistent member declaration order.
      // @see https://typescript-eslint.io/rules/member-ordering/
      '@typescript-eslint/member-ordering': [
        'error',
        {
          default: [
            'constructor',
            'static-field',
            'instance-field',
            'static-method',
            'instance-method',
          ],
        },
      ],
      // Enforce naming conventions for everything across a codebase.
      // @see https://typescript-eslint.io/rules/naming-convention/
      '@typescript-eslint/naming-convention': [
        'error',
        {
          selector: 'interface',
          format: ['PascalCase'],
          custom: {
            regex: '^I[A-Z]',
            match: false,
          },
        },
        {
          selector: 'enumMember',
          format: ['UPPER_CASE'],
        },
      ],
      // Disallow empty functions.
      // @see https://typescript-eslint.io/rules/no-empty-function/
      '@typescript-eslint/no-empty-function': 'error',
      // Disallow the declaration of empty interfaces.
      // @see https://typescript-eslint.io/rules/no-empty-interface/
      '@typescript-eslint/no-empty-interface': 'off',
      // Disallow the any type.
      // @see https://typescript-eslint.io/rules/no-explicit-any/
      '@typescript-eslint/no-explicit-any': 'error',
      // Reject unknown the same way as any: declare a concrete type.
      // @see https://typescript-eslint.io/rules/no-restricted-types/
      '@typescript-eslint/no-restricted-types': [
        'error',
        {
          types: {
            unknown: {
              message: 'Declare a concrete type instead of unknown.',
            },
          },
        },
      ],
      // Disallow TypeScript namespaces.
      // @see https://typescript-eslint.io/rules/no-namespace/
      '@typescript-eslint/no-namespace': ['error', { allowDeclarations: true }],
      // Disallow unused expressions.
      // @see https://typescript-eslint.io/rules/no-unused-expressions/
      '@typescript-eslint/no-unused-expressions': 'error',
      // Disallow unused variables.
      // @see https://typescript-eslint.io/rules/no-unused-vars/
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          ignoreRestSiblings: true,
          varsIgnorePattern: '^_',
        },
      ],
      // Enforce the use of for-of loop over the standard for loop where
      // possible.
      // @see https://typescript-eslint.io/rules/prefer-for-of/
      '@typescript-eslint/prefer-for-of': ['warn'],
      // Enforce using function types instead of interfaces with call
      // signatures.
      // @see https://typescript-eslint.io/rules/prefer-function-type/
      '@typescript-eslint/prefer-function-type': ['warn'],
      // Disallow two overloads that could be unified into one with a union
      // or an optional/rest parameter.
      // @see https://typescript-eslint.io/rules/unified-signatures/
      '@typescript-eslint/unified-signatures': 'warn',
      // Require the use of === and !==
      // @see https://eslint.org/docs/latest/rules/eqeqeq
      eqeqeq: ['error'],
      // Require for-in loops to include an if statement
      // @see https://eslint.org/docs/latest/rules/guard-for-in
      'guard-for-in': ['error'],
      // Disallow bitwise operators
      // @see https://eslint.org/docs/latest/rules/no-bitwise
      'no-bitwise': ['error'],
      // Disallow the use of arguments.caller or arguments.callee
      // @see https://eslint.org/docs/latest/rules/no-caller
      'no-caller': ['error'],
      // Disallow the use of console
      // @see https://eslint.org/docs/latest/rules/no-console
      'no-console': ['error', { allow: ['warn', 'error'] }],
      // Disallow duplicate module imports
      // @see https://eslint.org/docs/latest/rules/no-duplicate-imports
      'no-duplicate-imports': ['error'],
      // Disallow empty block statements
      // @see https://eslint.org/docs/latest/rules/no-empty
      'no-empty': 'error',
      // Disallow the use of eval()
      // @see https://eslint.org/docs/latest/rules/no-eval
      'no-eval': ['error'],
      // Disallow new operators with the String, Number, and Boolean objects
      // @see https://eslint.org/docs/latest/rules/no-new-wrappers
      'no-new-wrappers': ['error'],
      // Disallow throwing literals as exceptions
      // @see https://eslint.org/docs/latest/rules/no-throw-literal
      'no-throw-literal': ['error'],
      // Require let or const instead of var
      // @see https://eslint.org/docs/latest/rules/no-var
      'no-var': ['error'],
      // Require or disallow method and property shorthand syntax for object
      // literals
      // @see https://eslint.org/docs/latest/rules/object-shorthand
      'object-shorthand': ['error'],
      // Enforce variables to be declared either together or separately in
      // functions
      // @see https://eslint.org/docs/latest/rules/one-var
      'one-var': ['error', 'never'],
      // Require using arrow functions for callbacks
      // @see https://eslint.org/docs/latest/rules/prefer-arrow-callback
      'prefer-arrow-callback': 'off',
      // Require const declarations for variables that are never reassigned
      // after declared
      // @see https://eslint.org/docs/latest/rules/prefer-const
      'prefer-const': ['error'],
      // Enforce the consistent use of the radix argument when using
      // parseInt()
      // @see https://eslint.org/docs/latest/rules/radix
      radix: ['error'],
      // Enforce consistent spacing after the // or /* in a comment
      // @see https://eslint.org/docs/latest/rules/spaced-comment
      'spaced-comment': ['error', 'always', { block: { balanced: true } }],
    },
  },
  {
    // Holotape sources are different in two ways from the code in .scripts
    // and types, and this block accounts for both.
    //
    // First, they run on an Espruino interpreter rather than in Node or a
    // browser, so some rules argue against the platform.
    //
    // Second, these apps are tested on real hardware, where the emitted
    // JavaScript is the artifact. Rules whose fix rewrites a runtime
    // construct are therefore off: swapping `var` for `let`, `let` for
    // `const`, `==` for `===`, or a property for its shorthand each change
    // what ships to the device, and none of them can be applied on trust
    // without retesting the app on a Pip-Boy.
    //
    // They are switched off rather than left failing, because a warning
    // nobody can safely act on is worse than no warning. Modernising an
    // app's style is a deliberate change to make in its own commit, with a
    // device test behind it.
    files: ['holotapes/**/*.TS'],
    rules: {
      // --- Espruino platform ---------------------------------------------
      // Bit twiddling is the normal way to pack pixel, tile, and flag data
      // into the device's scarce memory, and 4bpp frame buffer work is
      // impossible without it.
      'no-bitwise': 'off',
      // eval() is the documented Espruino mechanism for loading sprite data
      // and lazily loading scene modules from the SD card, and there is no
      // module system to replace it.
      'no-eval': 'off',
      // require("fs") is how the device exposes the SD card.
      '@typescript-eslint/no-require-imports': 'off',
      // Uppercase .TS is an Espruino storage convention and is registered as
      // an extra parser extension. TypeScript performs the corresponding
      // global-name checks; ESLint's JavaScript-only rule cannot distinguish
      // ambient device declarations and type-only names in that extension.
      'no-undef': 'off',
      // The same extra-extension path applies JavaScript's function-scope
      // redeclaration model to TypeScript declarations. Leave this to the
      // TypeScript check so existing device-tested sources are not rewritten.
      'no-redeclare': 'off',
      // The "ram" and "jit" directives are bare string expressions, and
      // stripping them silently costs the performance they buy.
      '@typescript-eslint/no-unused-expressions': 'off',
      // An empty knob handler is not an oversight: registering one is how an
      // app claims the exclusive listener slot for a wheel it deliberately
      // ignores, so that the firmware does not act on it instead.
      '@typescript-eslint/no-empty-function': 'off',
      // Suppressions are not an escape hatch. `@ts-nocheck` and bare
      // `@ts-ignore` are rejected; `@ts-expect-error` needs a real reason.
      '@typescript-eslint/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': true,
          'ts-nocheck': true,
          'ts-check': false,
          minimumDescriptionLength: 10,
        },
      ],
      // Return types are erasable and do not change the JS shipped to the
      // device, so they are safe to require even on legacy migrations.
      '@typescript-eslint/explicit-function-return-type': [
        'error',
        { allowExpressions: true },
      ],
      // Type-position only; does not rewrite emitted JavaScript.
      '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
      // Swallowing a driver error with an empty catch is the standard way to
      // survive missing hardware or a missing file on this device. Other
      // empty blocks are still flagged.
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Grouped declarations keep an app's state block together at the top of
      // the file, which is the established layout in the audited holotape
      // sources this repository ports.
      'one-var': 'off',
      // Console output goes to the USB serial link, which is the only
      // debugging channel a holotape has.
      'no-console': 'off',
      'no-prototype-builtins': 'off',
      'no-throw-literal': 'off',
      'prefer-spread': 'off',
      'spaced-comment': 'off',

      // --- Would change the emitted JavaScript ---------------------------
      'prefer-const': 'off',
      'no-var': 'off',
      'object-shorthand': 'off',
      'no-useless-assignment': 'off',
      eqeqeq: 'off',
      '@typescript-eslint/prefer-for-of': 'off',
      // Removing an unused binding is a runtime change, and on this device a
      // real one: every declaration costs a scarce variable block. Dead code
      // should be deleted deliberately, with a device test behind it.
      '@typescript-eslint/no-unused-vars': 'off',
      // Renaming a shadowed binding is a runtime change. Espruino's flat
      // `let` scoping does make shadowing risky, but the build guards that
      // where it actually bites: the minifier runs without name mangling, so
      // no new collisions are introduced on the way to the device.
      '@typescript-eslint/no-shadow': 'off',
      // Adding the prototype guard, the radix argument, or a rest parameter
      // all rewrite the statement they fix.
      'guard-for-in': 'off',
      radix: 'off',
      'prefer-rest-params': 'off',

      // --- Still enforced -------------------------------------------------
      // Holotapes routinely create a bare object and bolt its members on over
      // the following lines, because building the whole literal at once costs
      // more Espruino variable blocks. Asserting the finished shape at the
      // declaration is the only way to type that without rewriting the app,
      // so object literal assertions are permitted here.
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'as', objectLiteralTypeAssertions: 'allow' },
      ],
    },
  },
  {
    // The build toolchain runs in Node, where console output is the point.
    files: ['.scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  // Holotape sources: no any / unknown escapes.
  {
    files: ['holotapes/**/*.{ts,TS}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-restricted-types': [
        'error',
        {
          types: {
            unknown: {
              message: 'Declare a concrete type instead of unknown.',
            },
          },
        },
      ],
    },
  },
  // Build scripts and ambient types may use unknown for Node catch/JSON edges.
  {
    files: ['.scripts/**/*.{ts,js}', 'types/**/*.d.ts'],
    rules: {
      '@typescript-eslint/no-restricted-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
]);
